version: 0.1
required_trunk_version: ">=1.22.8"

actions:
  definitions:
    - id: boops-export-pre-commit
      display_name: Export Boops Store
      run: "[ -f Cargo.toml ] && cargo run --quiet -- export || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: cargo-audit-pre-push
      display_name: Cargo Security Audit
      run: "[ -f Cargo.toml ] && mise exec -- cargo audit || true"
      triggers:
        - git_hooks: [pre-push]

    - id: cargo-deny-pre-push
      display_name: Cargo Dependency Check
      run: "[ -f Cargo.toml ] && mise exec -- cargo deny check --config .trunk/configs/deny.toml || true"
      triggers:
        - git_hooks: [pre-push]

    - id: cargo-test-pre-commit
      display_name: Cargo Tests
      run: "[ -f Cargo.toml ] && cargo test || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-test-pre-commit
      display_name: Pnpm Tests (Pre-commit)
      run: "[ -f package.json ] && mise exec -- pnpm test || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-test-pre-push
      display_name: Pnpm Tests (Pre-push)
      run: "[ -f package.json ] && mise exec -- pnpm test || true"
      triggers:
        - git_hooks: [pre-push]

    - id: pnpm-typecheck-pre-commit
      display_name: Pnpm Typecheck (Pre-commit)
      run: "[ -f package.json ] && mise exec -- pnpm typecheck || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-typecheck-pre-push
      display_name: Pnpm Typecheck (Pre-push)
      run: "[ -f package.json ] && mise exec -- pnpm typecheck || true"
      triggers:
        - git_hooks: [pre-push]

    - id: pnpm-audit-pre-push
      display_name: Pnpm Security Audit
      run: "[ -f package.json ] && mise exec -- pnpm audit --audit-level=high || true"
      triggers:
        - git_hooks: [pre-push]

    - id: yard-validate-pre-commit
      display_name: YARD Documentation Validation
      description: Validates YARD documentation before commit
      run: "[ -f Gemfile ] && mise run yard:validate || true"
      triggers:
        - git_hooks: [pre-commit]

  enabled:
    - boops-export-pre-commit
    - cargo-audit-pre-push
    - cargo-deny-pre-push
    - cargo-test-pre-commit
    - pnpm-audit-pre-push
    - pnpm-test-pre-commit
    - pnpm-test-pre-push
    - pnpm-typecheck-pre-commit
    - pnpm-typecheck-pre-push
    - trunk-announce
    - trunk-check-pre-commit
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
    - yard-validate-pre-commit

lint:
  definitions:
    - name: biome
      files:
        - javascript
        - typescript
        - json
        - jsonc
        - css
        - graphql
        - astro
        - svelte
        - vue
      description: A static analyzer for web projects
      commands:
        - name: lint
          output: regex
          parse_regex:
            ' *(?P<path>.*?):(?P<line>\d+):(?P<col>\d+) (?P<code>[^ ]+)(?:[^×]*\n).*×
            (?P<message>.*)\n'
          run: biome check ${target}
          success_codes: [0, 1]
          batch: true
          cache_results: true
          read_output_from: stderr
        - name: fmt
          output: rewrite
          run: biome check --fix "${target}"
          success_codes: [0, 1]
          batch: true
          cache_results: true
          formatter: true
          in_place: true
      tools: [biome]
      suggest_if: config_present
      direct_configs:
        - .trunk/configs/biome.json
        - biome.json
        - biome.jsonc
      affects_cache:
        - biome.json
        - biome.jsonc
        - .trunk/configs/biome.json
        - package.json
        - .editorconfig
      known_good_version: 2.3.11
      version_command:
        parse_regex: biome CLI version ${semver}
        run: biome --version

    - name: dprint
      tools: [dprint]
      files: [markdown]
      commands:
        - name: format
          run: dprint fmt ${target}
          output: rewrite
          success_codes: [0]
          formatter: true
          in_place: true
      direct_configs:
        - .trunk/configs/dprint.json
        - dprint.json
      affects_cache:
        - dprint.json
        - .trunk/configs/dprint.json
      suggest_if: config_present

    - name: rustfmt
      direct_configs:
        - .trunk/configs/rustfmt.toml
        - rustfmt.toml

    - name: serdi
      description: RDF syntax validator and canonical formatter
      files: [turtle]
      known_good_version: 0.32.6
      suggest_if: files_present
      commands:
        - name: format
          formatter: true
          output: rewrite
          run: serdi -o turtle ${target}
          success_codes: [0]
        - name: lint
          output: pass_fail
          read_output_from: stderr
          run: serdi -o turtle ${target}
          success_codes: [0, 1]

    - name: markdownlint
      direct_configs:
        - .trunk/configs/.markdownlint.json
        - .markdownlint.json

    - name: taplo
      direct_configs:
        - .trunk/configs/.taplo.toml
        - .taplo.toml
        - taplo.toml

  disabled:
    - prettier

  enabled:
    - bandit@1.9.3
    - biome@2.3.11
    - black@26.1.0
    - checkov@3.2.499
    - clippy@1.93.0
    - dprint@0.51.1
    - git-diff-check
    - isort@7.0.0
    - markdownlint@0.47.0
    - osv-scanner@2.3.2
    - ruff@0.14.14
    - rustfmt@1.93.0
    - serdi
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - taplo@0.10.0
    - trufflehog@3.92.5
    - yamllint@1.38.0

  exported_configs:
    - configs:
        - configs/.editorconfig
        - configs/.markdownlint.json
        - configs/.taplo.toml
        - configs/biome.json
        - configs/deny.toml
        - configs/dprint.json
        - configs/rustfmt.toml

  files:
    - name: turtle
      comments:
        - hash
      extensions:
        - ttl
    - name: vue
      comments:
        - html-tag
        - slashes-block
      extensions:
        - vue
    - name: jsonc
      extensions:
        - jsonc

  ignore:
    - linters: [ALL]
      paths:
        - "**/.git/**"
        - "**/node_modules/**"
        - .git/**
        - .next/**
        - .open-next/**
        - .sst/**
        - .trunk/**
        - .turbo/**
        - build/**
        - dist/**
        - node_modules/**
        - target/**
        - vendor/**

runtimes:
  enabled:
    - go@1.21.0
    - node@22.16.0
    - python@3.10.8

tools:
  definitions:
    - name: dprint
      runtime: node
      package: dprint
      shims: [dprint]
      known_good_version: 0.51.1

  enabled:
    - dprint@0.51.1
