version: 0.1
required_trunk_version: ">=1.22.8"

actions:
  definitions:
    - id: boops-export-pre-commit
      display_name: Export Boops Store
      run: "[ -f Cargo.toml ] && cargo run --quiet -- export || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: cargo-audit-pre-push
      display_name: Cargo Security Audit
      run: "[ -f Cargo.toml ] && mise exec -- cargo audit || true"
      triggers:
        - git_hooks: [pre-push]

    - id: cargo-deny-pre-push
      display_name: Cargo Dependency Check
      run: "[ -f Cargo.toml ] && mise exec -- cargo deny check --config .trunk/configs/deny.toml || true"
      triggers:
        - git_hooks: [pre-push]

    - id: cargo-test-pre-commit
      display_name: Cargo Tests
      run: "[ -f Cargo.toml ] && cargo test || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-test-pre-commit
      display_name: Pnpm Tests (Pre-commit)
      run: "[ -f package.json ] && mise exec -- pnpm test || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-test-pre-push
      display_name: Pnpm Tests (Pre-push)
      run: "[ -f package.json ] && mise exec -- pnpm test || true"
      triggers:
        - git_hooks: [pre-push]

    - id: pnpm-typecheck-pre-commit
      display_name: Pnpm Typecheck (Pre-commit)
      run: "[ -f package.json ] && mise exec -- pnpm typecheck || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: pnpm-typecheck-pre-push
      display_name: Pnpm Typecheck (Pre-push)
      run: "[ -f package.json ] && mise exec -- pnpm typecheck || true"
      triggers:
        - git_hooks: [pre-push]

    - id: pnpm-audit-pre-push
      display_name: Pnpm Security Audit
      run: "[ -f package.json ] && mise exec -- pnpm audit --audit-level=high || true"
      triggers:
        - git_hooks: [pre-push]

    - id: yard-validate-pre-commit
      display_name: YARD Documentation Validation
      description: Validates YARD documentation before commit
      run: "[ -f Gemfile ] && mise run yard:validate || true"
      triggers:
        - git_hooks: [pre-commit]

    - id: inspec-pre-push
      display_name: InSpec Compliance Tests
      description: Runs Chef/Cinc InSpec compliance profiles before push
      run: "[ -d cookbooks ] && inspec exec cookbooks/*/compliance/profiles/default --reporter cli || true"
      triggers:
        - git_hooks: [pre-push]

  enabled:
    - boops-export-pre-commit
    - cargo-audit-pre-push
    - cargo-deny-pre-push
    - cargo-test-pre-commit
    - pnpm-audit-pre-push
    - pnpm-test-pre-commit
    - pnpm-test-pre-push
    - pnpm-typecheck-pre-commit
    - pnpm-typecheck-pre-push
    - trunk-announce
    - trunk-check-pre-commit
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
    - yard-validate-pre-commit
    - inspec-pre-push

lint:
  definitions:
    # Extend biome with additional file types (jsonc, svelte, vue)
    # trunk-io/plugins only includes: astro, css, graphql, javascript, json, typescript
    - name: biome
      files:
        - javascript
        - typescript
        - json
        - jsonc
        - css
        - graphql
        - astro
        - svelte
        - vue

    # dprint is not in trunk-io/plugins - full definition required
    - name: dprint
      tools: [dprint]
      files: [markdown]
      commands:
        - name: format
          run: dprint fmt ${target}
          output: rewrite
          success_codes: [0]
          formatter: true
          in_place: true
      direct_configs:
        - .trunk/configs/dprint.json
        - dprint.json
      affects_cache:
        - dprint.json
        - .trunk/configs/dprint.json
      suggest_if: config_present

    # rubocop with mise-managed Ruby (version defined in project's .mise.toml)
    - name: rubocop
      environment:
        - name: PATH
          list: ["${home}/.local/share/mise/shims", "${env.PATH}"]

    # cookstyle for Chef/InSpec files (uses system cookstyle from Cinc Workstation)
    - name: cookstyle
      description: Chef/InSpec style linter (RuboCop-based)
      files: [ruby]
      suggest_if: never
      commands:
        - name: lint
          output: sarif
          run: /opt/cinc-workstation/bin/cookstyle --format json ${target}
          success_codes: [0, 1]
          batch: true
          parser:
            runtime: python
            run: python3 ${plugin}/configs/cookstyle_to_sarif.py
        - name: fix
          output: rewrite
          run: /opt/cinc-workstation/bin/cookstyle --auto-correct ${target}
          success_codes: [0, 1]
          in_place: true
          batch: true
          formatter: true
      direct_configs: [.rubocop.yml]
      issue_url_format: https://docs.chef.io/workstation/cookstyle/
      known_good_version: 7.32.8
      version_command:
        parse_regex: "Cookstyle ${semver}"
        run: /opt/cinc-workstation/bin/cookstyle --version

    # serdi is not in trunk-io/plugins - full definition required
    - name: serdi
      description: RDF syntax validator and canonical formatter
      files: [turtle]
      known_good_version: 0.32.6
      suggest_if: files_present
      commands:
        - name: format
          formatter: true
          output: rewrite
          run: serdi -o turtle ${target}
          success_codes: [0]
        - name: lint
          output: pass_fail
          read_output_from: stderr
          run: serdi -o turtle ${target}
          success_codes: [0, 1]

  disabled:
    - prettier

  enabled:
    - bandit@1.9.3
    - biome@2.3.11
    - black@26.1.0
    - checkov@3.2.499
    - clippy@1.93.0
    - dprint@0.51.1
    - git-diff-check
    - isort@7.0.0
    - markdownlint@0.47.0
    - osv-scanner@2.3.2
    - ruff@0.14.14
    - rustfmt@1.93.0
    - serdi
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - taplo@0.10.0
    - trufflehog@3.92.5
    - yamllint@1.38.0
    - rubocop

  exported_configs:
    - configs:
        - configs/.editorconfig
        - configs/.markdownlint.json
        - configs/.taplo.toml
        - configs/biome.json
        - configs/cookstyle_to_sarif.py
        - configs/deny.toml
        - configs/dprint.json
        - configs/rustfmt.toml
        - configs/.rubocop.yml

  files:
    - name: turtle
      comments:
        - hash
      extensions:
        - ttl
    - name: vue
      comments:
        - html-tag
        - slashes-block
      extensions:
        - vue
    - name: jsonc
      extensions:
        - jsonc
    - name: erb
      comments:
        - html-tag
      extensions:
        - erb
        - rhtml

  ignore:
    - linters: [ALL]
      paths:
        - "**/.git/**"
        - "**/node_modules/**"
        - .git/**
        - .next/**
        - .open-next/**
        - .sst/**
        - .trunk/**
        - .turbo/**
        - build/**
        - dist/**
        - node_modules/**
        - target/**
        - vendor/**

runtimes:
  enabled:
    - go@1.21.0
    - node@22.16.0
    - python@3.10.8

tools:
  definitions:
    - name: dprint
      runtime: node
      package: dprint
      shims: [dprint]
      known_good_version: 0.51.1

  enabled:
    - dprint@0.51.1
