version: 0.1

# Required Trunk CLI version
required_trunk_version: ">=1.22.8"

lint:
  # Custom file types
  files:
    - name: turtle
      extensions:
        - ttl
      comments:
        - hash

  # Default linters enabled for all projects that use this plugin
  enabled:
    - biome@2.3.11
    - git-diff-check
    - markdownlint@0.45.0
    - shellcheck@0.11.0
    - shfmt@3.6.0

  # Linter configuration overrides
  definitions:
    - name: taplo
      direct_configs:
        - .trunk/configs/.taplo.toml
        - .taplo.toml
        - taplo.toml

    - name: rustfmt
      direct_configs:
        - .trunk/configs/rustfmt.toml
        - rustfmt.toml

    # RDF Turtle linter/formatter
    # Requires: serdi installed via: sudo apt install serdi
    # Note: serdi produces canonical output (normalized, not pretty-printed)
    # Note: serdi removes comments by design - use RDF triples for documentation
    - name: serdi
      files: [turtle]
      description: RDF syntax validator and canonical formatter from the Serd library
      commands:
        - name: format
          formatter: true
          run: serdi -o turtle ${target}
          output: rewrite
          success_codes: [0]
        - name: lint
          run: serdi -o turtle ${target}
          output: pass_fail
          success_codes: [0, 1]
          read_output_from: stderr
      suggest_if: files_present
      known_good_version: 0.32.6

  # Global ignore patterns
  ignore:
    - linters: [ALL]
      paths:
        - node_modules/**
        - .git/**
        - "**/.git/**"
        - "**/node_modules/**"
        - vendor/**
        - dist/**
        - build/**
        - .trunk/**

  # Export config files to consuming repositories
  # These become available in .trunk/configs/ automatically
  exported_configs:
    - configs:
        - configs/.markdownlint.json
        - configs/.editorconfig
        - configs/biome.json
        - configs/.taplo.toml
        - configs/rustfmt.toml
        - configs/deny.toml

actions:
  enabled:
    - trunk-check-pre-commit
    - trunk-fmt-pre-commit
